INSERT INTO animals (genus, genus_lat, species, species_lat, description)
 VALUES ('Žirafa', 'Giraffa','','camelopardalis', 'Žirafa (Giraffa camelopardalis) je mohutný sudokopytník, v současnosti nejvyšší ze všech suchozemských živočišných druhů. Samci dosahují velikosti od 4,8 až do 5,5 metru a váží až 900 kilogramů (rekordní jedinec, zastřelený roku 1934 v Keni byl vysoký 5,87 metru a vážil zhruba 2000 kg). Samice jsou obecně trochu menší a lehčí. V zajetí se dožívá zhruba 25 let. Žije ve skupinách, ale ty nejsou stálé. Za život vystřídá větší množství skupin. Ač původem z Afriky je žirafa příbuzná s jelenem či krávou');
INSERT INTO animals (genus, genus_lat, species, species_lat, description)
 VALUES ('Zebra','Equus','stepní','quagga','Hmotnost: 220-330 kg Délka těla: 210-250 cm Výška v kohoutku: 120-140 cm Ocas: 43-57 cm');
INSERT INTO animals (genus, genus_lat, species, species_lat, description)
 VALUES ('Lev','Panthera','pustinný','leo','Samci, dobře rozpoznatelní podle hřívy, mohou vážit 150-225 kg. Samice dosahují hmotnosti 120-150 kg. Největší africký lev držený v zajetí vážil 366 kg. Samci dosahují délky 170-250 cm. Samice zhruba 140-175 cm. Ocas měří 70-100 cm a je zakončen střapcem, který v sobě ukrývá zhruba 5 mm dlouhý trn. Lvi jsou jediné šelmy, které tento střapec mají. Jeho funkce je dosud neznámá. V divočině se lvi dožívají až 15 let, v zajetí to může být až o deset let více. Kožich bývá zbarven různě - Od světle žluté přes načervenalou až po tmavě hnědou. Hříva samců bývá světle žlutá až černá. Střapec na ocasu je vždy černý.');
INSERT INTO animals (genus, genus_lat, species, species_lat, description)
 VALUES ('Hroch','Hippopotamus','obojživelný','amphibius','Hroch má zavalité tělo s velkou hlavou s široce rozevíratelnou tlamou. Má krátké, sloupovité nohy se čtyřmi prsty, krajní dva prsty má dobře vyvinuty a při chůzi došlapuje na všechny prsty. Mezi prsty má krátkou plovací blánu. Protože tráví většinu času ve vodě (zhruba 18 hodin denně) má uzavíratelné ušní boltce a nozdry.');
INSERT INTO animals (genus, genus_lat, species, species_lat, description)
 VALUES ('Tygr','Panthera','džunglový','tigris','V minulosti byl v mnoha poddruzích prakticky po celé Asii, od Turecka až po Koreu a Indonésii. Dnes jsou, hlavně kvůli člověku, některé poddruhy vyhubeny a tygr je ohroženým druhem. Věk uváděný u jednotlivých poddruhů je údajem ze zajetí - ve volné přírodě se tygři dožívají podstatně méně (kolem deseti let). Jednotlivé poddruhy tygra se od sebe liší velikostí i zbarvením, tedy kresbou.');
INSERT INTO animals (genus, genus_lat, species, species_lat, description)
 VALUES ('Smilodon','Smilodon','populator','populator','Dospělý Smilodon váil asi 55-300 kg, v závislosti na druhu. Měl krátký ocas, silné nohy, svalnatý krk a dlouhé špičáky. I když byl trochu menší než dnešní tygr, byl extrémně silný a měl podobnou stavbu těla jako medvěd.');
INSERT INTO animals (genus, genus_lat, species, species_lat, description)
 VALUES ('Gibon','Hylobates','běloruký','lar','Gibon lar je, stejně jako jiní giboni, vysoce specializovaný na život v korunách stromů. Má krátký nos, nízkou lebku a dopředu mířící oči, které umožňují vynikající prostorové vidění. Paže jsou asi o 40 % delší než pánevní končetiny, prsty ruky jsou dlouhé a hákovité, palec je naproti tomu malý a vzdálený od ostatních prstů. Palec u nohy se může postavit do opozice vůči ostatním prstům. Giboni mají sedací hrboly, které jim umožňují spát ve větvích, ocas chybí.');
INSERT INTO animals (genus, genus_lat, species, species_lat, description)
 VALUES ('Šimpanz','Pan','učenlivý','troglodytes','Společně s bonobem je nejbližším žijícím příbuzným člověka a je mu ze všech primátů nejpodobnější. Srst má tmavou, lysé části těla bývají u některých poddruhů světlá. Dorůstá obvykle výšky 65-95 cm a hmotnosti od 44 do 75 kg. Přestože se převážně živí rostlinnou stravou, doplňuje svůj jídelníček o termity, mravence a jiný hmyz. V některých oblastech tvoří část jeho jídelničku i maso získané lovem (malé antilopy, kočkodani a mláďata paviánů). Samice je březí osm měsíců, rodí jediné mládě. Pohlavně dospělí je po 6-10 letech života.');
INSERT INTO animals (genus, genus_lat, species, species_lat, description)
 VALUES ('Žralok','Carcharodon','bílý','carcharias','Žralok bílý je velký žralok čeledi Lamnidae vyskytující se v pobřežních vodách. Je považován za člověku nejnebezpečnějšího žraloka a jako takový byl dlouhodobě systematicky huben námořníky a rybáři. Jeho pronásledování ještě zesílilo po uvedení úspěného filmu Čelisti, takže se v současné době čelí bezprostřední hrozbě vyhubení. Ve skutečnosti tito žraloci člověka systematicky neloví.');
INSERT INTO animals (genus, genus_lat, species, species_lat, description)
 VALUES ('Losos','Salmo','obecný','salar','Losos obecný či losos atlantský je dravá tažná ryba z čeledi lososovitých, která žije většinu života v moři. Dospělí jedinci během svého života migrují proti proudu řek hluboko do vnitrozemí kontinentů, aby v rodných řekách vyvedli další generaci. Mladí lososi pak v horních tocích řek tráví začátek života, než se vydají zpět do moře, aby zde rychle dospěli a vydali se zpět do rodných řek.');
INSERT INTO animals (genus, genus_lat, species, species_lat, description)
 VALUES ('Kapr','Cyprinus','obecný','carpio','Kapr obecný se dlouhodobě vyskytuje v řekách a jezerech úmoří Černého moře, Kaspického moře a Aralského jezera, rozsah původního přirozeného areálu je však nejasné. Postupně byl pro svou užitkovou hodnotu rozšířen na většinu území kontinentu. Pro jeho chov byly vybudovány celé rybniční soustavy, hlavně v období středověku.Kapr obecný byl zavlečen do Austrálie, kde je považován za extrémně nebezpečný invazivní druh, který má velmi devastující vliv na tamní sladkovodní ekosystémy.');

INSERT INTO animal_movement (animal_id,valid_from,valid_to,geometry)
 VALUES (1,null,null,SDO_GEOMETRY(2003,8307,NULL,SDO_ELEM_INFO_ARRAY(1,1003,3),SDO_ORDINATE_ARRAY(1,1, 5,7)));
