INSERT INTO animals (genus, genus_lat, species, species_lat, description)
 VALUES ('Žirafa', 'Giraffa','','camelopardalis', 'Žirafa (Giraffa camelopardalis) je mohutný sudokopytník, v souèasnosti nejvyšší ze všech suchozemských živoèišných druhù. Samci dosahují velikosti od 4,8 až do 5,5 metru a váží až 900 kilogramù (rekordní jedinec, zastøelený roku 1934 v Keni byl vysoký 5,87 metru a vážil zhruba 2000 kg). Samice jsou obecnì trochu menší a lehèí. V zajetí se dožívá zhruba 25 let. Žije ve skupinách, ale ty nejsou stálé. Za život vystøídá vìtší množství skupin. Aè pùvodem z Afriky je žirafa pøíbuzná s jelenem èi krávou');
INSERT INTO animals (genus, genus_lat, species, species_lat, description)
 VALUES ('Zebra','Equus','stepní','quagga','Hmotnost: 220-330 kg Délka tìla: 210-250 cm Výška v kohoutku: 120-140 cm Ocas: 43-57 cm');
INSERT INTO animals (genus, genus_lat, species, species_lat, description)
 VALUES ('Lev','Panthera','pustinný','leo','Samci, dobøe rozpoznatelní podle høívy, mohou vážit 150-225 kg. Samice dosahují hmotnosti 120-150 kg. Nejvìtší africký lev držený v zajetí vážil 366 kg. Samci dosahují délky 170-250 cm. Samice zhruba 140-175 cm. Ocas mìøí 70-100 cm a je zakonèen støapcem, který v sobì ukrývá zhruba 5 mm dlouhý trn. Lvi jsou jediné šelmy, které tento støapec mají. Jeho funkce je dosud neznámá. V divoèinì se lvi dožívají až 15 let, v zajetí to mùže být až o deset let více. Kožich bývá zbarven rùznì - Od svìtle žluté pøes naèervenalou až po tmavì hnìdou. Høíva samcù bývá svìtle žlutá až èerná. Bøišní partie bývají svìtlejší, støapec na ocasu je vždy èerný.');
INSERT INTO animals (genus, genus_lat, species, species_lat, description)
 VALUES ('Hroch','Hippopotamus','obojživelný','amphibius','Hroch má zavalité tìlo s velkou hlavou s široce rozevíratelnou tlamou. Má krátké, sloupovité nohy se ètyømi prsty, krajní dva prsty má dobøe vyvinuty a pøi chùzi došlapuje na všechny prsty. Mezi prsty má krátkou plovací blánu. Protože tráví vìtšinu èasu ve vodì (zhruba 18 hodin dennì) má uzavíratelné ušní boltce a nozdry.');
INSERT INTO animals (genus, genus_lat, species, species_lat, description)
 VALUES ('Tygr','Panthera','džunglový','tigris','V minulosti byl v mnoha poddruzích rozšíøen prakticky po celé Asii, od Turecka až po Koreu a Indonésii. Dnes jsou, hlavnì kvùli èlovìku, nìkteré poddruhy vyhubeny a tygr je ohroženým druhem. Vìk uvádìný u jednotlivých poddruhù je údajem ze zajetí - ve volné pøírodì se tygøi dožívají podstatnì ménì (kolem deseti let). Jednotlivé poddruhy tygra se od sebe liší velikostí i zbarvením, tedy kresbou.');
INSERT INTO animals (genus, genus_lat, species, species_lat, description)
 VALUES ('Smilodon','Smilodon','populator','populator','Dospìlý Smilodon vážil asi 55-300 kg, v závislosti na druhu. Mìl krátký ocas, silné nohy, svalnatý krk a dlouhé špièáky. I když byl trochu menší než dnešní tygr, byl extrémnì silný mìl podobnou stavbu tìla jako medvìd.');
INSERT INTO animals (genus, genus_lat, species, species_lat, description)
 VALUES ('Gibon','Hylobates','bìloruký','lar','Gibon lar je, stejnì jako jiní giboni, vysoce specializovaný na život v korunách stromù. Má krátký nos, nízkou lebku a dopøedu míøící oèi, které umožòují vynikající prostorové vidìní. Paže jsou asi o 40 % delší než pánevní konèetiny, prsty ruky jsou dlouhé a hákovité, palec je naproti tomu malý a vzdálený od ostatních prstù. Palec u nohy se mùže postavit do opozice vùèi ostatním prstùm. Giboni mají sedací hrboly, které jim umožòují spát ve vìtvích, ocas chybí.');
INSERT INTO animals (genus, genus_lat, species, species_lat, description)
 VALUES ('Šimpanz','Pan','uèenlivý','troglodytes','Spoleènì s bonobem je nejbližším žijícím pøíbuzným èlovìka a je mu ze všech primátù nejpodobnìjší. Srst má tmavou, lysé èásti tìla bývají u nìkterých poddruhù svìtlé. Dorùstá obvykle výšky 65-95 cm (šimpanz èago kolem 120 cm) a hmotnosti od 44 do 75 kg. Pøestože se pøevážnì živí rostlinnou stravou, doplòuje svùj jídelníèek o termity, mravence a jiný hmyz. V nìkterých oblastech tvoøí èást jeho jídelníèku i maso získané lovem (malé antilopy, koèkodani a mláïata paviánù). Samice je bøezí osm mìsícù, rodí jediné mládì. Pohlavnì dospìlý je po 6–10 letech života.');
INSERT INTO animals (genus, genus_lat, species, species_lat, description)
 VALUES ('Žralok','Carcharodon','bílý','carcharias','Žralok bílý je velký žralok èeledi Lamnidae vyskytující se v pobøežních vodách. Je považován za èlovìku nejnebezpeènìjšího žraloka a jako takový byl dlouhodobì systematicky huben námoøníky a rybáøi. Jeho pronásledování ještì zesílilo po uvedení úspìšného filmu Èelisti, takže se v souèasné dobì èelí bezprostøední hrozbì vyhubení. Ve skuteènosti tito žraloci èlovìka systematicky neloví.');
INSERT INTO animals (genus, genus_lat, species, species_lat, description)
 VALUES ('Losos','Salmo','obecný','salar','Losos obecný èi losos atlantský je dravá tažná ryba z èeledi lososovitých, která žije vìtšinu života v moøi. Dospìlí jedinci bìhem svého života migrují proti proudu øek hluboko do vnitrozemí kontinentù, aby v rodných øekách vyvedli další generaci. Mladí lososi pak v horních tocích øek tráví zaèátek života, než se vydají zpìt do moøe, aby zde rychle dospìli a vydali se zpìt do rodných øek.');
INSERT INTO animals (genus, genus_lat, species, species_lat, description)
 VALUES ('Kapr','Cyprinus','obecný','carpio','Kapr obecný se dlouhodobì vyskytuje v øekách a jezerech úmoøí Èerného moøe, Kaspického moøe a Aralského jezera, rozsah pùvodního pøirozeného areálu je však nejasný. Postupnì byl pro svou užitkovou hodnotu rozšíøen na vìtšinu území kontinentu. Pro jeho chov byly vybudovány celé rybnièní soustavy, hlavnì v období støedovìku.Kapr obecný byl zavleèen do Austrálie, kde je považován za extrémnì nebezpeèný invazívní druh, který má velmi devastující vliv na tamní sladkovodní ekosystémy.');

INSERT INTO animal_movement (animal_id,valid_from,valid_to,geometry)
 VALUES (1,null,null,SDO_GEOMETRY(2003,8307,NULL,SDO_ELEM_INFO_ARRAY(1,1003,3),SDO_ORDINATE_ARRAY(1,1, 5,7)));
